---
- group:
    name: backupusers

- user:
    name: "{{hostvars[item].backup_user}}"
    comment: "Backup user for {{item}}"
    group: backupusers
    home: /
    createhome: no
  loop: "{{groups.backup_clients}}"

- file:
    path: /home/backup/
    group: backupusers
    state: directory
    mode: '0750'

- file:
    path: "/home/backup/{{hostvars[item].backup_user}}"
    owner: root
    group: backupusers
    state: directory
    recurse: yes
    mode: '0750'
  loop: "{{groups.backup_clients}}"

- file:
    path: "/home/backup/{{hostvars[item].backup_user}}/.ssh"
    owner: "{{hostvars[item].backup_user}}"
    group: backupusers
    state: directory
    recurse: yes
    mode: '0750'
  loop: "{{groups.backup_clients}}"

- file:
    path: "/home/backup/{{hostvars[item].backup_user}}/{{item}}"
    owner: "{{hostvars[item].backup_user}}"
    group: backupusers
    state: directory
    recurse: yes
  loop: "{{groups.backup_clients}}"

# Install SSHd config for implements scponly and chrooting
# TODO: change this to use lineinfile if needed to not intefere with
# other roles that touch this
- copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
  notify:
    - reload SSHd

# TODO set up authorized_hosts
- copy:
    src: "ssh_keys/{{item}}.id_rsa.pub"
    dest: "/home/backup/{{hostvars[item].backup_user}}/.ssh/authorized_keys"
    owner: "{{hostvars[item].backup_user}}"
    group: backupusers
  loop: "{{groups.backup_clients}}"

- include: secondary.yml
