---
- name: Install necessary packages for backup
  apt:
    name:
      - gnupg
      - backupninja
      - duplicity
    state: present

- name: install secondary backup ssh key
  copy:
    src: ssh_keys/secondary.id_rsa
    dest: /root/.ssh/id_rsa.secondary
    owner: root
    group: root
    mode: '0600'

- name: copy backup GPG key
  copy:
    src: gpg_keys/secondary.gpg
    dest: /root/gnupg.import.gpg
    owner: root
    group: root
    mode: '0600'
  tags: backup

- shell: gpg -K "{{gpg_keyid}}"
  register: key_installed
  ignore_errors: True

- name: import GPG key
  command: gpg --allow-secret-key-import --import /root/gnupg.import.gpg
  when: key_installed|failed
  tags: backup

# We need to do these two steps as GPG doesn't let us set trust with
# --batch, nor does it let us set trust on import. it looks weird but
# it could be worse.
- name: setup GPG trust
  template:
    src: owner_trust.j2
    dest: /root/owner_trust

- name: Import GPG trust
  command: gpg --import-ownertrust /root/owner_trust

- name: install duplicity job
  template:
    src: secondary.dup.j2
    dest: /etc/backup.d/secondary.dup
    mode: '0700'

- name: install backupninja conf
  template:
    src: backupninja.conf.j2
    dest: /etc/backupninja.conf
    owner: root
    group: root
    mode: '0600'
