# All GPG keys must be full fingerprints, not 8-digit.

[backup_primary]
mymainserver.example.com secondary_server=mysecondaryserver.example.com gpg_keyid=FIXME1 gpg_passphrase=FIXME2

[backup_secondary]
mysecondaryserver.example.com

[backup_clients]
# backup_include and backup_exclude are required, even if they're empty lists.
# If you want to change the default backup_paths list, you can define it per-host here.
myserverwithsomebackups.example.com backup_user=oldbackup gpg_passphrase=FIXME2 backup_include=[] backup_exclude='["/home/backup"]' gpg_keyid=FIXME
vmserver.example.com backup_user=vmserver gpg_passphrase=FIXME backup_include=[] backup_exclude='["/srv/libvirt"]' gpg_keyid=FIXME
