---
- hosts: backup_primary
  become: true
  roles:
    - backup_server

- hosts: backup_secondary
  become: true
  roles:
    - backup_secondary

- hosts: backup_clients
  become: true
  roles:
    - backup_client
