---

- hosts: all
  user: root
  sudo: true
  roles:
    - common

- hosts: backup_primary
  user: root
  roles:
    - backup_server

- hosts: backup_secondary
  user: root
  roles:
    - backup_secondary

- hosts: backup_clients
  user: root
  sudo: true
  roles:
    - backup_client
