---
- user:
    name: "{{secondary_user}}"
    comment: "Secondary backup user"
    home: /

- group:
    name: "{{secondary_user}}"

- file:
    path: "/home/{{secondary_user}}"
    owner: root
    group: "{{secondary_user}}"
    state: directory
    recurse: yes

- file:
    path: "/home/{{secondary_user}}/.ssh"
    owner: "{{secondary_user}}"
    group: "{{secondary_user}}"
    state: directory
    recurse: yes

- file:
    path: "/home/{{secondary_user}}/primary"
    owner: "{{secondary_user}}"
    group: "{{secondary_user}}"
    state: directory
    recurse: yes

- copy:
    src: ssh_keys/secondary.id_rsa.pub
    dest: "/home/{{secondary_user}}/.ssh/authorized_keys"
    owner: "{{secondary_user}}"
    group: "{{secondary_user}}"

# Install SSHd config for implements scponly and chrooting
# TODO: Should do this with lineinfile so we do not intefere with
# other roles that might need to touch this
- template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
  notify:
    - reload SSHd
