---
- group:
    name: "{{ secondary_user }}"

- user:
    name: "{{ secondary_user }}"
    group: "{{ secondary_user }}"
    comment: "Secondary backup user"
    createhome: no
    home: /

- file:
    path: "/home/{{ secondary_user }}"
    owner: root
    group: "{{ secondary_user }}"
    state: directory
    recurse: yes

- file:
    path: "/home/{{ secondary_user }}/.ssh"
    owner: "{{ secondary_user }}"
    group: "{{ secondary_user }}"
    state: directory
    mode: '0700'
    recurse: yes

- file:
    path: "/home/{{ secondary_user }}/primary"
    owner: "{{ secondary_user }}"
    group: "{{ secondary_user }}"
    state: directory
    mode: '0700'
    recurse: yes

- copy:
    src: ssh_keys/secondary.id_rsa.pub
    dest: "/home/{{ secondary_user }}/.ssh/authorized_keys"
    owner: "{{ secondary_user }}"
    group: "{{ secondary_user }}"
    mode: '0600'

- blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match user {{ secondary_user }}
         ChrootDirectory /home/%u
         AuthorizedKeysFile /home/%u/.ssh/authorized_keys
         X11Forwarding no
         AllowTcpForwarding no
         ForceCommand internal-sftp
    insertafter: EOF
  notify:
    - restart SSHd
