---
- apt: state=installed name={{item}}
  with_items:
    - fail2ban

- name: Set timezone
  copy: content='Etc/UTC'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  notify:
    - update timezone
